In [1]:
import sys

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# read the data set
df = pd.read_csv('../data/breast-cancer.txt')

# Replace the missing or non numeric values
df.dropna(inplace=True)
df=df._get_numeric_data()



# Drop the ID column
df.drop(['id'], 1, inplace=True)
# Create features and labels arrays
X = np.array(df.drop(['class'], 1))
y = np.array(df['class'])
# Scale the features array X
# The scaling of the data is important for convergence of the model
# There are different types of scaling
scaler1 = MinMaxScaler(feature_range=(0,1))
scaler1.fit(X)
X = scaler1.transform(X)

# scaler2 = StandardScaler()
# scaler2.fit(X)
# X = scaler2.transform(X)

# Transform the feature array y to a binary array 0 or 1
y = np.array(y==4).astype(int)

# Split the arrays into training and test arrays
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train,X_test, y_train, y_test)




[[0.66666667 0.11111111 0.33333333 ... 0.44444444 0.33333333 0.22222222]
 [1.         1.         1.         ... 1.         1.         0.66666667]
 [0.33333333 0.         0.         ... 0.11111111 0.         0.        ]
 ...
 [0.11111111 0.         0.         ... 0.11111111 0.         0.        ]
 [0.88888889 0.77777778 0.77777778 ... 0.33333333 1.         0.33333333]
 [0.         0.         0.11111111 ... 0.11111111 0.         0.        ]] [[0.11111111 0.44444444 0.22222222 ... 0.66666667 0.44444444 0.        ]
 [0.77777778 0.22222222 0.44444444 ... 0.         0.55555556 0.11111111]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [1.         0.33333333 0.22222222 ... 0.55555556 0.44444444 0.11111111]
 [0.22222222 0.         0.         ... 0.         0.         0.        ]
 [0.33333333 0.         0.22222222 ... 0.11111111 0.         0.        ]] [1 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 1 1 0 0 1
 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 

/home/mazhar/anaconda3/envs/AICourse/lib/python3.7/site-packages/ipykernel_launcher.py:15: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  from ipykernel import kernelapp as app
/home/mazhar/anaconda3/envs/AICourse/lib/python3.7/site-packages/ipykernel_launcher.py:17: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only


In [5]:
np.save('X_train.npy',X_train)
np.save('X_test.npy', X_test)
np.save('y_train.npy',y_train)
np.save('y_test.npy', y_test)

In [11]:
print(np.load('X_train.npy'))

2
